### ISSUE TITLE
Container exception

### ISSUE THREAD

**Issue by Viperoo** [core23/DompdfBundle#8]
Hi,

I got Exception when i want to use your bundle in symfony 4.0.4 project.

```
(1/1) FatalThrowableError
Type error: Return value of ContainerBEs80iu\srcDevDebugProjectContainer::{closure}() must be an instance of dompdf, instance of Core23\DompdfBundle\Wrapper\DompdfWrapper returned
```

Generated container

```
}, 'dompdf' => function (): \dompdf {
    return ($this->services['dompdf'] ?? $this->load(__DIR__.'/getDompdfService.php'));
``` 

In service 

```
  public static function getSubscribedServices()
    {
        return array_merge(parent::getSubscribedServices(), [
            Breadcrumbs::class,
            'translator' => TranslatorInterface::class,
            Templates::class,
            'dompdf'
        ]);
    }
```

But when i change `getSubscribedServices` to `'dompdf' => DompdfWrapper::class` or `'dompdf' => DompdfWrapperInterface::class` i got 

```
The service "App\Controller\Tools\LogController" has a dependency on a non-existent service "Core23\DompdfBundle\Wrapper\DompdfWrapper".
```

services.yaml

```
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true   
        autoconfigure: true
        public: false     # <------
```

I try `2.1` and `master`, `PHP 7.2.2`. Dompdf `v0.8.2`

thanks for your work
greetings
